/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package baiguixemanagement;
import javax.swing.*;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.sql.*;
//import manh_javaSwing.trangChu;
/**
 *
 * @author Lucyfer
 */
public class quanLyXeVao extends javax.swing.JFrame {

    /**
     * Creates new form giaoDien
     */
    public quanLyXeVao() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        vexe = new javax.swing.JLabel();
        ngaygiovao = new javax.swing.JLabel();
        biensoxe = new javax.swing.JTextField();
        enter = new javax.swing.JButton();
        Cam2 = new javax.swing.JLabel();
        choosefile1 = new javax.swing.JButton();
        choosefile2 = new javax.swing.JButton();
        label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Trang chủ ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton7.setText("Quản lí xe ra bãi ");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Quản lí nhân viên");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("Chờ quẹt thẻ ");

        jLabel26.setText("Ngày vào :");

        jLabel27.setText("Vé xe:");

        jLabel28.setText("Biển số xe:");

        vexe.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                vexeAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        ngaygiovao.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ngaygiovaoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        biensoxe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                biensoxeMouseClicked(evt);
            }
        });

        enter.setText("Enter");
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ngaygiovao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vexe, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(biensoxe, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(enter)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ngaygiovao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vexe, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(biensoxe, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addComponent(enter))
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(230, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(231, 231, 231))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );

        Cam2.setBackground(new java.awt.Color(255, 255, 255));
        Cam2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cam2.setText("Cam2");
        Cam2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        choosefile1.setText("Ảnh xe vào ");
        choosefile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosefile1ActionPerformed(evt);
            }
        });

        choosefile2.setText("ảnh vào đằng trước ");
        choosefile2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosefile2ActionPerformed(evt);
            }
        });

        label.setBackground(new java.awt.Color(255, 255, 255));
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(choosefile1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(choosefile2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Cam2, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(choosefile1)
                    .addComponent(choosefile2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cam2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        close();
        trangChu pi = new trangChu();
        pi.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        close();
        quanLyXeRa x = new quanLyXeRa();
        x.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        close();
        quanLyNhanVien nv = new quanLyNhanVien();
        nv.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void choosefile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosefile1ActionPerformed
 // Tạo một file chooser dialog
    JFileChooser fileChooser = new JFileChooser();

    // Thiết lập bộ lọc cho file chooser
    FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("Hình ảnh", "jpg", "png");
    fileChooser.setFileFilter(imageFilter);
    fileChooser.setMultiSelectionEnabled(false);

    // Mở file chooser dialog và lấy đường dẫn tệp đã chọn
    int result = fileChooser.showDialog(this, "Chọn file");
    if (result == JFileChooser.APPROVE_OPTION) {
        File selectedFile = fileChooser.getSelectedFile();

        // Chỉnh kích thước hình ảnh cho phù hợp với nhãn
        ImageIcon imageIcon = new ImageIcon(selectedFile.getAbsolutePath());
        Image image = imageIcon.getImage().getScaledInstance(693, 282, Image.SCALE_SMOOTH);
        imageIcon.setImage(image);

        // Đặt hình ảnh vào nhãn
        label.setIcon(imageIcon);
    }
       
    }//GEN-LAST:event_choosefile1ActionPerformed

    private void vexeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_vexeAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_vexeAncestorAdded

    private void ngaygiovaoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ngaygiovaoAncestorAdded
           
   
    }//GEN-LAST:event_ngaygiovaoAncestorAdded
    private static String generateRandomString(String prefix, int length) {
        Random random = new Random();
        StringBuilder sb = new StringBuilder();
    
        sb.append(prefix);

        for (int i = 0; i < length; i++) {
           int randomDigit = random.nextInt(5);
           sb.append(randomDigit);
        }

        return sb.toString();
    }

    private static int generateRandomNumber(int min, int max) {
        Random random = new Random();
        return random.nextInt(max - min + 1) + min;
    }    
    

    
    
    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
        
        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/doan_oop", "root", ""))
           {
            String selectQuery = "SELECT MANV FROM NHANVIEN ORDER BY RAND() LIMIT 1";
            Statement selectStatement = conn.createStatement();
            ResultSet resultSet = selectStatement.executeQuery(selectQuery);

            // Lấy dữ liệu từ kết quả truy vấn
            String randomData = null;
            if (resultSet.next()) {
                randomData = resultSet.getString("MANV");
            }

            // Kiểm tra xem có dữ liệu ngẫu nhiên được lấy hay không
            
                
            // Chuẩn bị truy vấn chèn dữ liệu
            String query = "INSERT INTO vexe (MATHE, THOIGIANVAO, MANV) VALUES (?, ?, ?)";
            PreparedStatement statement = conn.prepareStatement(query);
            // Tạo số ngẫu nhiên có 5 chữ số
            Random random = new Random();
            int randomNumber = 100000 + random.nextInt(900000);
            String mathe = String.valueOf(randomNumber);
            // Thiết lập giá trị thời gian cho truy vấn
            // Lấy thời gian hiện tại
            Date currentTime = new Date();
            // Định dạng thời gian theo đúng định dạng
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            String formattedTime = dateFormat.format(currentTime);
            
            //String bienSoXe = biensoxe.getText();
            
            // Thiết lập giá trị thời gian cho truy vấn
            statement.setInt(1, randomNumber);
            statement.setString(2, formattedTime);
            if (randomData != null) {
                statement.setString(3, randomData);
            }
            // Thực hiện chèn dữ liệu
            int rowsAffected = statement.executeUpdate();
            if(rowsAffected > 0){
                JOptionPane.showMessageDialog(null, "Thêm dữ liệu thành công");               
            }
            else{
               JOptionPane.showMessageDialog(null, "Không thêm được dữ liệu");
           }
            System.out.println("Chèn dữ liệu thành công.");
            
            
            // hiển thị ra label
            ngaygiovao.setText(formattedTime);
            vexe.setText(mathe);
            
            
            //phần lấy makhuvuc xuống 
            String selectQuery1 = "SELECT MAKHUVUC FROM XE ORDER BY RAND() LIMIT 1";
            Statement selectStatement1 = conn.createStatement();
            ResultSet resultSet1 = selectStatement1.executeQuery(selectQuery1);

            // Lấy dữ liệu từ kết quả truy vấn
            String randomData1 = null;
            if (resultSet1.next()) {
                randomData1 = resultSet1.getString("MAKHUVUC");
            }
            // phần bảng xe trên mysql  
            
            String query1 = "INSERT INTO xe (BIENSOXE, MATHE, MAKHUVUC,STT_VITRI ) VALUES (?, ?, ?, ?)";
            PreparedStatement statement1 = conn.prepareStatement(query1);
            String bsx = biensoxe.getText();
            // Tạo chuỗi chứa chữ cố định và số ngẫu nhiên
            String randomStringVitri = generateRandomString("VI TRI ", 1) + generateRandomNumber(1, 9);
            
            statement1.setString(1, bsx);
            statement1.setInt(2,randomNumber);
            if(randomData1 != null){
                statement1.setString(3, randomData1);
            
            }
             
            statement1.setString(4, randomStringVitri);
            statement1.executeUpdate();
            
            
            
            // 
        } catch (SQLException e) {
            e.printStackTrace();
            
        }
        
    
    }//GEN-LAST:event_enterActionPerformed

    private void choosefile2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosefile2ActionPerformed
        // TODO add your handling code here:
         // Tạo một file chooser dialog
    JFileChooser fileChooser = new JFileChooser();

    // Thiết lập bộ lọc cho file chooser
    FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("Hình ảnh", "jpg", "png");
    fileChooser.setFileFilter(imageFilter);
    fileChooser.setMultiSelectionEnabled(false);

    // Mở file chooser dialog và lấy đường dẫn tệp đã chọn
    int result = fileChooser.showDialog(this, "Chọn file");
    if (result == JFileChooser.APPROVE_OPTION) {
        File selectedFile = fileChooser.getSelectedFile();

        // Chỉnh kích thước hình ảnh cho phù hợp với nhãn
        ImageIcon imageIcon = new ImageIcon(selectedFile.getAbsolutePath());
        Image image = imageIcon.getImage().getScaledInstance(693, 282, Image.SCALE_SMOOTH);
        imageIcon.setImage(image);

        // Đặt hình ảnh vào nhãn
        Cam2.setIcon(imageIcon);
    }//GEN-LAST:event_choosefile2ActionPerformed
    }
    private void biensoxeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_biensoxeMouseClicked
        biensoxe.setText("");
    }//GEN-LAST:event_biensoxeMouseClicked
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quanLyXeRa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quanLyXeRa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quanLyXeRa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quanLyXeRa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quanLyXeVao().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cam2;
    private javax.swing.JTextField biensoxe;
    private javax.swing.JButton choosefile1;
    private javax.swing.JButton choosefile2;
    private javax.swing.JButton enter;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel label;
    private javax.swing.JLabel ngaygiovao;
    private javax.swing.JLabel vexe;
    // End of variables declaration//GEN-END:variables

}